/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 basketball.glb 
Author: afurokn (https://sketchfab.com/afurokn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basketball-2343abdae7674f46ad85071858db93c6
Title: Basketball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Basketball(props) {
  const { nodes, materials } = useGLTF('/models/basketball.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Basketball_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Basketball_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/basketball.glb')
