/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 oreo_cupcake.glb 
Author: Mustafa Duyar (https://sketchfab.com/mustafaduyar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oreo-cupcake-142dc666e43045dc82e4ddbf58b0d381
Title: Oreo Cupcake
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cupcake(props) {
  const { nodes, materials } = useGLTF('/models/oreo_cupcake.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.polySurface3_surfaceShader1_0.geometry} material={materials.surfaceShader1} />
        <mesh geometry={nodes.pDisc1_lambert3_0.geometry} material={materials.lambert3} position={[0, -3.752, 0]} scale={79.815} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/oreo_cupcake.glb')
