/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gameboy.glb 
Author: grimmorf (https://sketchfab.com/grimmorf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gameboy-4a1da0cefa904c4eae895338bd6f3334
Title: GAMEBOY
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Gameboy(props) {
  const { nodes, materials } = useGLTF('/models/gameboy.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.001, -0.003]} rotation={[-Math.PI / 2, 0, 0]} scale={1.481}>
        <group position={[-0.012, 3.59, 0.468]}>
          <mesh geometry={nodes.game_low_mat_default_0.geometry} material={materials.mat_default} />
          <mesh geometry={nodes.Box_low_mat_default_0.geometry} material={materials.mat_default} position={[-3.236, 1.25, 7.248]} />
          <mesh geometry={nodes.Cyl_1_low_mat_default_0.geometry} material={materials.mat_default} position={[-3.924, 0.716, 3.144]} />
          <mesh geometry={nodes.Cyl_2_low_mat_default_0.geometry} material={materials.mat_default} position={[3.859, 1.439, 2.801]} />
          <mesh geometry={nodes.Button_low_mat_default_0.geometry} material={materials.mat_default} position={[0.012, 2.816, 0.012]} />
          <mesh geometry={nodes.Open_low_mat_default_0.geometry} material={materials.mat_default} position={[0.006, 2.438, -0.822]} />
          <mesh geometry={nodes.Cartridge_low001_mat_default_0.geometry} material={materials.mat_default} position={[0.128, 2.524, 3.413]} />
          <mesh geometry={nodes.Object001_mat_default_0.geometry} material={materials.mat_default} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/gameboy.glb')
