/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 low_poly_classical_guitar.glb 
Author: gazorpinhas (https://sketchfab.com/gazorpinhas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-classical-guitar-90ca0a9c525e47d48a68146fd7bd97e3
Title: Low Poly Classical Guitar
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/low_poly_classical_guitar.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.081, 0.827, 0.044]} scale={[0.005, 0.01, 0.006]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Materiais.006']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Materiais.005']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Materiais} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Materiais.003']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Materiais.004']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Materiais.007']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Materiais.008']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Materiais.011']} />
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_classical_guitar.glb')
