/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 modern_slim_laptop.glb 
Author: Blaž Mraz (https://sketchfab.com/Mraz3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-slim-laptop-fbf172f8b14241feab581dcb1fbcd475
Title: Modern Slim Laptop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/models/modern_slim_laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 0.024, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[0, 0.122, 0.008]} rotation={[1.358, 0, 0]}>
            <mesh geometry={nodes.Screen_Frame_Screen_Frame_0.geometry} material={materials.Screen_Frame} />
            <mesh geometry={nodes.Screen_Frame_Screen_Shiny_Border_0.geometry} material={materials.Screen_Shiny_Border} />
            <mesh geometry={nodes.Screen_Frame_Base_0.geometry} material={materials.Base} />
            <mesh geometry={nodes.Screen_Screen_0.geometry} material={materials.Screen} />
          </group>
          <mesh geometry={nodes.Modern_Slim_Laptop_Base_0.geometry} material={materials.Base} />
          <mesh geometry={nodes.Modern_Slim_Laptop_Touchpad_0.geometry} material={materials.Touchpad} />
          <mesh geometry={nodes.Modern_Slim_Laptop_Plastic_Black_Ports_0.geometry} material={materials.Plastic_Black_Ports} />
          <mesh geometry={nodes.Modern_Slim_Laptop_Lights_0.geometry} material={materials.Lights} />
          <mesh geometry={nodes.Keyboard_Keyboard_0.geometry} material={materials.Keyboard} position={[-0.067, 0.001, 0.009]} rotation={[0.023, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/modern_slim_laptop.glb')
